# GitHub Pages 配置

## 项目名称
title: Deep DMS Reactor

## 项目描述  
description: Molecular Structure Visualization Center

## 主题
theme: jekyll-theme-minimal

## 生成设置
markdown: kramdown
plugins:
  - jekyll-feed
